# render.yaml

services:
- type: web
name: phantom-flash
env: prod
plan: free
envVars:
- key: TELEGRAM_BOT_TOKEN
value: your_bot_token_here
- key: ADMIN_ID
value: your_telegram_id_here
buildCommand: npm ci --only=production
startCommand: node bot.js
healthCheckPath: /health